[[project]]
name = "first project"
desc = "about my first project"
tags = ["", ""]
links = [
{ name = "link 1", url = "https://github.com/likithjai/" },
{ name = "link 1", url = "https://github.com/likithjai/" },
]


[[project]]
name = "second project"
desc = "about my second project"
tags = ["", ""]
links = [
{ name = "link 1", url = "https://github.com/likithjai/" },
{ name = "link 1", url = "https://github.com/likithjai/" },
]
